### ISSUE TITLE
Add MySQL support

### ISSUE THREAD

**Issue by phortx** [redhotvengeance/deep_thought#2]
Since my (and many others) server(s) run on MySQL and I don't want to install a second database management system just for one app, MySQL suppor or even a complete database abstraction would be really nice.

(Good work so far, loving it!)

**Comment by redhotvengeance** [comment]
This should be fairly straightforward. Deep Thought uses Active Record as an ORM, so extending it to use multiple database types won't take much tweaking.

**Comment by redhotvengeance** [comment]
Multiple database adapters support is added, and new gem (v0.2.1) has been released.

Info on database adapters is in the bottom of the [setup section of the docs](https://github.com/redhotvengeance/deep_thought#setup).

**Comment by phortx** [comment]
Nice job! Thank you. :)
